# ----------------------------------------------------------------------------------------------------------------------
# MyBatis / MyBatis-Plus
# ----------------------------------------------------------------------------------------------------------------------
mybatis-plus:
  global-config:
    banner: off
    db-config:
      id-type: auto
      table-prefix: "t_"
      table-underline: true
  type-aliases-package: "examples.mybatis.domain"
  mapper-locations:
    - "classpath*:/mybatis-mapper/**/*.xml"
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true
