# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  config:
    activate:
      on-profile:
        - debug
debug: true
---

# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: "examples-mybatis"
  profiles:
    include: [ ]
  aop:
    auto: true
  main:
    web-application-type: servlet
    banner-mode: off
    allow-bean-definition-overriding: true
    lazy-initialization: false
    log-startup-info: true
    cloud-platform: none
    register-shutdown-hook: true
  jackson:
    locale: "zh_CN"
    time-zone: "Asia/Shanghai"
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    default-property-inclusion: always
    serialization:
      indent-output: true
      fail-on-self-references: true
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
      write-null-map-values: true
      write-empty-json-arrays: true
      write-single-elem-arrays-unwrapped: false
      write-enums-using-to-string: true
    deserialization:
      fail-on-unknown-properties: false
  lifecycle:
    timeout-per-shutdown-phase: "30s"
  jmx:
    enabled: false
    unique-names: true
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://10.211.55.3:3306/mybatis?useSSL=true&verifyServerCertificate=false"
    username: "root"
    password: "root"
    hikari:
      connection-test-query: "SELECT 1"

# ----------------------------------------------------------------------------------------------------------------------
# Actuator
# ----------------------------------------------------------------------------------------------------------------------
management:
  endpoint:
    shutdown:
      enabled: false
    env:
      enabled: true
    configprops:
      enabled: false
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include:
            - "ping"
            - "livenessStateProbeIndicator"
        readiness:
          include:
            - "ping"
            - "livenessStateProbeIndicator"
            - "readinessStateProbeIndicator"
  info:
    git:
      enabled: true
      mode: simple
    java:
      enabled: true
    env:
      enabled: false
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
